# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: overlay.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'overlay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roverlay.proto\"Y\n\x0cQueryRequest\x12\x12\n\nquery_type\x18\x01 \x01(\t\x12\x14\n\x0cquery_params\x18\x02 \x01(\t\x12\x0c\n\x04hops\x18\x03 \x03(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\"g\n\rQueryResponse\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x05\x12\x15\n\rtotal_records\x18\x03 \x01(\x03\x12\x0c\n\x04hops\x18\x04 \x03(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"0\n\x0c\x43hunkRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\"v\n\rChunkResponse\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x0f\n\x07is_last\x18\x05 \x01(\x08\x12\x0e\n\x06status\x18\x06 \x01(\t\"\x10\n\x0eMetricsRequest\"\x83\x02\n\x0fMetricsResponse\x12\x12\n\nprocess_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0c\n\x04team\x18\x03 \x01(\t\x12\x17\n\x0f\x61\x63tive_requests\x18\x04 \x01(\x05\x12\x14\n\x0cmax_capacity\x18\x05 \x01(\x05\x12\x12\n\nis_healthy\x18\x06 \x01(\x08\x12\x12\n\nqueue_size\x18\x07 \x01(\x05\x12\x1e\n\x16\x61vg_processing_time_ms\x18\x08 \x01(\x02\x12\x19\n\x11\x64\x61ta_files_loaded\x18\t \x01(\x05\x12\x19\n\x11\x66\x61irness_strategy\x18\n \x01(\t\x12\x13\n\x0brecent_logs\x18\x0b \x03(\t\"#\n\x0fShutdownRequest\x12\x10\n\x08graceful\x18\x01 \x01(\x08\"\"\n\x10ShutdownResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xca\x01\n\x0bOverlayNode\x12(\n\x05Query\x12\r.QueryRequest\x1a\x0e.QueryResponse\"\x00\x12+\n\x08GetChunk\x12\r.ChunkRequest\x1a\x0e.ChunkResponse\"\x00\x12\x31\n\nGetMetrics\x12\x0f.MetricsRequest\x1a\x10.MetricsResponse\"\x00\x12\x31\n\x08Shutdown\x12\x10.ShutdownRequest\x1a\x11.ShutdownResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'overlay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=17
  _globals['_QUERYREQUEST']._serialized_end=106
  _globals['_QUERYRESPONSE']._serialized_start=108
  _globals['_QUERYRESPONSE']._serialized_end=211
  _globals['_CHUNKREQUEST']._serialized_start=213
  _globals['_CHUNKREQUEST']._serialized_end=261
  _globals['_CHUNKRESPONSE']._serialized_start=263
  _globals['_CHUNKRESPONSE']._serialized_end=381
  _globals['_METRICSREQUEST']._serialized_start=383
  _globals['_METRICSREQUEST']._serialized_end=399
  _globals['_METRICSRESPONSE']._serialized_start=402
  _globals['_METRICSRESPONSE']._serialized_end=661
  _globals['_SHUTDOWNREQUEST']._serialized_start=663
  _globals['_SHUTDOWNREQUEST']._serialized_end=698
  _globals['_SHUTDOWNRESPONSE']._serialized_start=700
  _globals['_SHUTDOWNRESPONSE']._serialized_end=734
  _globals['_OVERLAYNODE']._serialized_start=737
  _globals['_OVERLAYNODE']._serialized_end=939
# @@protoc_insertion_point(module_scope)
